spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24 hours


