# application-dev.yaml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: localhost
    port: 1025
    username:
    password:

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.yourblog: DEBUG

app:
  cors:
    allowed-origins: http://localhost:4200
  upload:
    directory: uploads/dev

  cache:
    timeToLiveSeconds: 3600

  mail:
    from: dev@yourblog.com
    base-url: http://localhost:8080

server:
  error:
    include-stacktrace: always

jwt:
  secret: dev-secret-key-should-be-very-long-and-secure
  expiration: 86400000 # 24 hours